table M_SEXO
	lineageTag: 709e5911-0b75-4f61-8ef8-f5edb1af476a

	column Sexo
		dataType: string
		lineageTag: 13d8b195-d045-4bb1-bc70-88b206a084f7
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column Orden
		dataType: int64
		formatString: 0
		lineageTag: cebe6cfd-b3c4-4f67-8af5-f839e9678723
		summarizeBy: sum
		sourceColumn: Orden

		annotation SummarizationSetBy = Automatic

	column EsTotal
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 27f02cd5-6af5-42aa-b79d-d297e224c9d9
		summarizeBy: none
		sourceColumn: EsTotal

		annotation SummarizationSetBy = Automatic

	partition M_SEXO = m
		mode: import
		source =
				let
				    Source1 = Table.SelectColumns(H_MEDIA_SUELDOS_EDAD, {"Sexo"}),
				    Source2 = Table.SelectColumns(H_MEDIA_SUELDOS_ANUALES, {"Sexo"}),
				    Source3 = Table.SelectColumns(H_SUELDOS_POR_ACTIVIDAD, {"Sexo"}),
				    AppendAll = Table.Combine({Source1, Source2, Source3}),
				    Trimmed = Table.TransformColumns(AppendAll, {{"Sexo", each Text.Proper(Text.Trim(_)), type text}}),
				    Distinct = Table.Distinct(Trimmed),
				    WithOrden = Table.AddColumn(Distinct, "Orden", each if [Sexo] = "Hombres" then 1 else if [Sexo] = "Mujeres" then 2 else if [Sexo] = "Ambos Sexos" then 3 else null, Int64.Type),
				    WithEsTotal = Table.AddColumn(WithOrden, "EsTotal", each [Sexo]="Ambos Sexos", type logical),
				    Sorted = Table.Sort(WithEsTotal, {{"Orden", Order.Ascending}, {"Sexo", Order.Ascending}})
				in
				    Sorted

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

