table VIVIENDAS
	lineageTag: b412a3d9-5412-473c-a701-d2093a7e2a06

	column CCAA
		dataType: string
		lineageTag: 2d359add-f133-40f8-af5a-28b1303b043c
		summarizeBy: none
		sourceColumn: CCAA

		annotation SummarizationSetBy = Automatic

	column 'Tipo Vivienda'
		dataType: string
		lineageTag: a2ddd66b-08d8-4285-aadd-0b3dbdaadfaf
		summarizeBy: none
		sourceColumn: TipoVivienda

		annotation SummarizationSetBy = Automatic

	column Indicador
		dataType: string
		lineageTag: 8df2b527-2909-4ccd-a260-787b38c55afe
		summarizeBy: none
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 88964a65-d361-4eb6-8679-ae03ef6e43ee
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: f1179770-69ed-4a39-8ec1-cd688c9744df
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition VIVIENDAS = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jaume\Documents\Porfolio\Dashboard_Datos_ES\raw_data\Vivienda.xlsx"), null, true),
				    #"tabla-1" = Origen{[Name="tabla-25171"]}[Data],
				    #"Filas superiores quitadas" = Table.Skip(#"tabla-1",6),
				    #"Tabla transpuesta" = Table.Transpose(#"Filas superiores quitadas"),
				    #"Rellenar hacia abajo" = Table.FillDown(#"Tabla transpuesta",{"Column1"}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Rellenar hacia abajo",{"Column2", "Column1", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88"}),
				    #"Columnas combinadas" = Table.CombineColumns(#"Columnas reordenadas",{"Column2", "Column1"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Periodo"),
				    #"Tabla transpuesta1" = Table.Transpose(#"Columnas combinadas"),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tabla transpuesta1", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Encabezados promovidos",{{"  -  ", "CCAA1"}}),
				    #"Texto recortado" = Table.TransformColumns(#"Columnas con nombre cambiado",{{"CCAA1", Text.Trim, type text}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Texto recortado", "TipoVivienda", each if [CCAA1] = "General" then "General" else if [CCAA1] = "Vivienda nueva" then "Vivienda nueva" else if [CCAA1] = "Vivienda segunda mano" then "Vivienda segunda mano" else null),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "CCAA", each if [TipoVivienda] = null then [CCAA1] else null),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Columna condicional agregada1",{"CCAA1"}),
				    #"Columnas reordenadas1" = Table.ReorderColumns(#"Columnas quitadas",{"CCAA", "TipoVivienda", "2025T1 - Índice", "2024T4 - Índice", "2024T3 - Índice", "2024T2 - Índice", "2024T1 - Índice", "2023T4 - Índice", "2023T3 - Índice", "2023T2 - Índice", "2023T1 - Índice", "2022T4 - Índice", "2022T3 - Índice", "2022T2 - Índice", "2022T1 - Índice", "2021T4 - Índice", "2021T3 - Índice", "2021T2 - Índice", "2021T1 - Índice", "2020T4 - Índice", "2020T3 - Índice", "2020T2 - Índice", "2020T1 - Índice", "2019T4 - Índice", "2019T3 - Índice", "2019T2 - Índice", "2019T1 - Índice", "2018T4 - Índice", "2018T3 - Índice", "2018T2 - Índice", "2018T1 - Índice", "2017T4 - Índice", "2017T3 - Índice", "2017T2 - Índice", "2017T1 - Índice", "2016T4 - Índice", "2016T3 - Índice", "2016T2 - Índice", "2016T1 - Índice", "2015T4 - Índice", "2015T3 - Índice", "2015T2 - Índice", "2015T1 - Índice", "2014T4 - Índice", "2014T3 - Índice", "2014T2 - Índice", "2014T1 - Índice", "2013T4 - Índice", "2013T3 - Índice", "2013T2 - Índice", "2013T1 - Índice", "2012T4 - Índice", "2012T3 - Índice", "2012T2 - Índice", "2012T1 - Índice", "2011T4 - Índice", "2011T3 - Índice", "2011T2 - Índice", "2011T1 - Índice", "2010T4 - Índice", "2010T3 - Índice", "2010T2 - Índice", "2010T1 - Índice", "2009T4 - Índice", "2009T3 - Índice", "2009T2 - Índice", "2009T1 - Índice", "2008T4 - Índice", "2008T3 - Índice", "2008T2 - Índice", "2008T1 - Índice", "2007T4 - Índice", "2007T3 - Índice", "2007T2 - Índice", "2007T1 - Índice", "2025T1 - Variación trimestral", "2024T4 - Variación trimestral", "2024T3 - Variación trimestral", "2024T2 - Variación trimestral", "2024T1 - Variación trimestral", "2023T4 - Variación trimestral", "2023T3 - Variación trimestral", "2023T2 - Variación trimestral", "2023T1 - Variación trimestral", "2022T4 - Variación trimestral", "2022T3 - Variación trimestral", "2022T2 - Variación trimestral", "2022T1 - Variación trimestral", "2021T4 - Variación trimestral", "2021T3 - Variación trimestral", "2021T2 - Variación trimestral", "2021T1 - Variación trimestral", "2020T4 - Variación trimestral", "2020T3 - Variación trimestral", "2020T2 - Variación trimestral", "2020T1 - Variación trimestral", "2019T4 - Variación trimestral", "2019T3 - Variación trimestral", "2019T2 - Variación trimestral", "2019T1 - Variación trimestral", "2018T4 - Variación trimestral", "2018T3 - Variación trimestral", "2018T2 - Variación trimestral", "2018T1 - Variación trimestral", "2017T4 - Variación trimestral", "2017T3 - Variación trimestral", "2017T2 - Variación trimestral", "2017T1 - Variación trimestral", "2016T4 - Variación trimestral", "2016T3 - Variación trimestral", "2016T2 - Variación trimestral", "2016T1 - Variación trimestral", "2015T4 - Variación trimestral", "2015T3 - Variación trimestral", "2015T2 - Variación trimestral", "2015T1 - Variación trimestral", "2014T4 - Variación trimestral", "2014T3 - Variación trimestral", "2014T2 - Variación trimestral", "2014T1 - Variación trimestral", "2013T4 - Variación trimestral", "2013T3 - Variación trimestral", "2013T2 - Variación trimestral", "2013T1 - Variación trimestral", "2012T4 - Variación trimestral", "2012T3 - Variación trimestral", "2012T2 - Variación trimestral", "2012T1 - Variación trimestral", "2011T4 - Variación trimestral", "2011T3 - Variación trimestral", "2011T2 - Variación trimestral", "2011T1 - Variación trimestral", "2010T4 - Variación trimestral", "2010T3 - Variación trimestral", "2010T2 - Variación trimestral", "2010T1 - Variación trimestral", "2009T4 - Variación trimestral", "2009T3 - Variación trimestral", "2009T2 - Variación trimestral", "2009T1 - Variación trimestral", "2008T4 - Variación trimestral", "2008T3 - Variación trimestral", "2008T2 - Variación trimestral", "2008T1 - Variación trimestral", "2007T4 - Variación trimestral", "2007T3 - Variación trimestral", "2007T2 - Variación trimestral", "2007T1 - Variación trimestral", "2025T1 - Variación anual", "2024T4 - Variación anual", "2024T3 - Variación anual", "2024T2 - Variación anual", "2024T1 - Variación anual", "2023T4 - Variación anual", "2023T3 - Variación anual", "2023T2 - Variación anual", "2023T1 - Variación anual", "2022T4 - Variación anual", "2022T3 - Variación anual", "2022T2 - Variación anual", "2022T1 - Variación anual", "2021T4 - Variación anual", "2021T3 - Variación anual", "2021T2 - Variación anual", "2021T1 - Variación anual", "2020T4 - Variación anual", "2020T3 - Variación anual", "2020T2 - Variación anual", "2020T1 - Variación anual", "2019T4 - Variación anual", "2019T3 - Variación anual", "2019T2 - Variación anual", "2019T1 - Variación anual", "2018T4 - Variación anual", "2018T3 - Variación anual", "2018T2 - Variación anual", "2018T1 - Variación anual", "2017T4 - Variación anual", "2017T3 - Variación anual", "2017T2 - Variación anual", "2017T1 - Variación anual", "2016T4 - Variación anual", "2016T3 - Variación anual", "2016T2 - Variación anual", "2016T1 - Variación anual", "2015T4 - Variación anual", "2015T3 - Variación anual", "2015T2 - Variación anual", "2015T1 - Variación anual", "2014T4 - Variación anual", "2014T3 - Variación anual", "2014T2 - Variación anual", "2014T1 - Variación anual", "2013T4 - Variación anual", "2013T3 - Variación anual", "2013T2 - Variación anual", "2013T1 - Variación anual", "2012T4 - Variación anual", "2012T3 - Variación anual", "2012T2 - Variación anual", "2012T1 - Variación anual", "2011T4 - Variación anual", "2011T3 - Variación anual", "2011T2 - Variación anual", "2011T1 - Variación anual", "2010T4 - Variación anual", "2010T3 - Variación anual", "2010T2 - Variación anual", "2010T1 - Variación anual", "2009T4 - Variación anual", "2009T3 - Variación anual", "2009T2 - Variación anual", "2009T1 - Variación anual", "2008T4 - Variación anual", "2008T3 - Variación anual", "2008T2 - Variación anual", "2008T1 - Variación anual", "2007T4 - Variación anual", "2007T3 - Variación anual", "2007T2 - Variación anual", "2007T1 - Variación anual", "2025T1 - Variación en lo que va de año", "2024T4 - Variación en lo que va de año", "2024T3 - Variación en lo que va de año", "2024T2 - Variación en lo que va de año", "2024T1 - Variación en lo que va de año", "2023T4 - Variación en lo que va de año", "2023T3 - Variación en lo que va de año", "2023T2 - Variación en lo que va de año", "2023T1 - Variación en lo que va de año", "2022T4 - Variación en lo que va de año", "2022T3 - Variación en lo que va de año", "2022T2 - Variación en lo que va de año", "2022T1 - Variación en lo que va de año", "2021T4 - Variación en lo que va de año", "2021T3 - Variación en lo que va de año", "2021T2 - Variación en lo que va de año", "2021T1 - Variación en lo que va de año", "2020T4 - Variación en lo que va de año", "2020T3 - Variación en lo que va de año", "2020T2 - Variación en lo que va de año", "2020T1 - Variación en lo que va de año", "2019T4 - Variación en lo que va de año", "2019T3 - Variación en lo que va de año", "2019T2 - Variación en lo que va de año", "2019T1 - Variación en lo que va de año", "2018T4 - Variación en lo que va de año", "2018T3 - Variación en lo que va de año", "2018T2 - Variación en lo que va de año", "2018T1 - Variación en lo que va de año", "2017T4 - Variación en lo que va de año", "2017T3 - Variación en lo que va de año", "2017T2 - Variación en lo que va de año", "2017T1 - Variación en lo que va de año", "2016T4 - Variación en lo que va de año", "2016T3 - Variación en lo que va de año"}),
				    #"Rellenar hacia abajo1" = Table.FillDown(#"Columnas reordenadas1",{"CCAA"}),
				    #"Filas inferiores quitadas" = Table.RemoveLastN(#"Rellenar hacia abajo1",4),
				    #"Filas filtradas" = Table.SelectRows(#"Filas inferiores quitadas", each ([TipoVivienda] <> null)),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas filtradas", "CCAA1", each if Text.StartsWith([CCAA], "Nacional") then "Nacional"
				else Text.Trim(Text.AfterDelimiter([CCAA], " "))),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Personalizada agregada",{"CCAA"}),
				    #"Columnas reordenadas2" = Table.ReorderColumns(#"Columnas quitadas1",{"CCAA1", "TipoVivienda", "2025T1 - Índice", "2024T4 - Índice", "2024T3 - Índice", "2024T2 - Índice", "2024T1 - Índice", "2023T4 - Índice", "2023T3 - Índice", "2023T2 - Índice", "2023T1 - Índice", "2022T4 - Índice", "2022T3 - Índice", "2022T2 - Índice", "2022T1 - Índice", "2021T4 - Índice", "2021T3 - Índice", "2021T2 - Índice", "2021T1 - Índice", "2020T4 - Índice", "2020T3 - Índice", "2020T2 - Índice", "2020T1 - Índice", "2019T4 - Índice", "2019T3 - Índice", "2019T2 - Índice", "2019T1 - Índice", "2018T4 - Índice", "2018T3 - Índice", "2018T2 - Índice", "2018T1 - Índice", "2017T4 - Índice", "2017T3 - Índice", "2017T2 - Índice", "2017T1 - Índice", "2016T4 - Índice", "2016T3 - Índice", "2016T2 - Índice", "2016T1 - Índice", "2015T4 - Índice", "2015T3 - Índice", "2015T2 - Índice", "2015T1 - Índice", "2014T4 - Índice", "2014T3 - Índice", "2014T2 - Índice", "2014T1 - Índice", "2013T4 - Índice", "2013T3 - Índice", "2013T2 - Índice", "2013T1 - Índice", "2012T4 - Índice", "2012T3 - Índice", "2012T2 - Índice", "2012T1 - Índice", "2011T4 - Índice", "2011T3 - Índice", "2011T2 - Índice", "2011T1 - Índice", "2010T4 - Índice", "2010T3 - Índice", "2010T2 - Índice", "2010T1 - Índice", "2009T4 - Índice", "2009T3 - Índice", "2009T2 - Índice", "2009T1 - Índice", "2008T4 - Índice", "2008T3 - Índice", "2008T2 - Índice", "2008T1 - Índice", "2007T4 - Índice", "2007T3 - Índice", "2007T2 - Índice", "2007T1 - Índice", "2025T1 - Variación trimestral", "2024T4 - Variación trimestral", "2024T3 - Variación trimestral", "2024T2 - Variación trimestral", "2024T1 - Variación trimestral", "2023T4 - Variación trimestral", "2023T3 - Variación trimestral", "2023T2 - Variación trimestral", "2023T1 - Variación trimestral", "2022T4 - Variación trimestral", "2022T3 - Variación trimestral", "2022T2 - Variación trimestral", "2022T1 - Variación trimestral", "2021T4 - Variación trimestral", "2021T3 - Variación trimestral", "2021T2 - Variación trimestral", "2021T1 - Variación trimestral", "2020T4 - Variación trimestral", "2020T3 - Variación trimestral", "2020T2 - Variación trimestral", "2020T1 - Variación trimestral", "2019T4 - Variación trimestral", "2019T3 - Variación trimestral", "2019T2 - Variación trimestral", "2019T1 - Variación trimestral", "2018T4 - Variación trimestral", "2018T3 - Variación trimestral", "2018T2 - Variación trimestral", "2018T1 - Variación trimestral", "2017T4 - Variación trimestral", "2017T3 - Variación trimestral", "2017T2 - Variación trimestral", "2017T1 - Variación trimestral", "2016T4 - Variación trimestral", "2016T3 - Variación trimestral", "2016T2 - Variación trimestral", "2016T1 - Variación trimestral", "2015T4 - Variación trimestral", "2015T3 - Variación trimestral", "2015T2 - Variación trimestral", "2015T1 - Variación trimestral", "2014T4 - Variación trimestral", "2014T3 - Variación trimestral", "2014T2 - Variación trimestral", "2014T1 - Variación trimestral", "2013T4 - Variación trimestral", "2013T3 - Variación trimestral", "2013T2 - Variación trimestral", "2013T1 - Variación trimestral", "2012T4 - Variación trimestral", "2012T3 - Variación trimestral", "2012T2 - Variación trimestral", "2012T1 - Variación trimestral", "2011T4 - Variación trimestral", "2011T3 - Variación trimestral", "2011T2 - Variación trimestral", "2011T1 - Variación trimestral", "2010T4 - Variación trimestral", "2010T3 - Variación trimestral", "2010T2 - Variación trimestral", "2010T1 - Variación trimestral", "2009T4 - Variación trimestral", "2009T3 - Variación trimestral", "2009T2 - Variación trimestral", "2009T1 - Variación trimestral", "2008T4 - Variación trimestral", "2008T3 - Variación trimestral", "2008T2 - Variación trimestral", "2008T1 - Variación trimestral", "2007T4 - Variación trimestral", "2007T3 - Variación trimestral", "2007T2 - Variación trimestral", "2007T1 - Variación trimestral", "2025T1 - Variación anual", "2024T4 - Variación anual", "2024T3 - Variación anual", "2024T2 - Variación anual", "2024T1 - Variación anual", "2023T4 - Variación anual", "2023T3 - Variación anual", "2023T2 - Variación anual", "2023T1 - Variación anual", "2022T4 - Variación anual", "2022T3 - Variación anual", "2022T2 - Variación anual", "2022T1 - Variación anual", "2021T4 - Variación anual", "2021T3 - Variación anual", "2021T2 - Variación anual", "2021T1 - Variación anual", "2020T4 - Variación anual", "2020T3 - Variación anual", "2020T2 - Variación anual", "2020T1 - Variación anual", "2019T4 - Variación anual", "2019T3 - Variación anual", "2019T2 - Variación anual", "2019T1 - Variación anual", "2018T4 - Variación anual", "2018T3 - Variación anual", "2018T2 - Variación anual", "2018T1 - Variación anual", "2017T4 - Variación anual", "2017T3 - Variación anual", "2017T2 - Variación anual", "2017T1 - Variación anual", "2016T4 - Variación anual", "2016T3 - Variación anual", "2016T2 - Variación anual", "2016T1 - Variación anual", "2015T4 - Variación anual", "2015T3 - Variación anual", "2015T2 - Variación anual", "2015T1 - Variación anual", "2014T4 - Variación anual", "2014T3 - Variación anual", "2014T2 - Variación anual", "2014T1 - Variación anual", "2013T4 - Variación anual", "2013T3 - Variación anual", "2013T2 - Variación anual", "2013T1 - Variación anual", "2012T4 - Variación anual", "2012T3 - Variación anual", "2012T2 - Variación anual", "2012T1 - Variación anual", "2011T4 - Variación anual", "2011T3 - Variación anual", "2011T2 - Variación anual", "2011T1 - Variación anual", "2010T4 - Variación anual", "2010T3 - Variación anual", "2010T2 - Variación anual", "2010T1 - Variación anual", "2009T4 - Variación anual", "2009T3 - Variación anual", "2009T2 - Variación anual", "2009T1 - Variación anual", "2008T4 - Variación anual", "2008T3 - Variación anual", "2008T2 - Variación anual", "2008T1 - Variación anual", "2007T4 - Variación anual", "2007T3 - Variación anual", "2007T2 - Variación anual", "2007T1 - Variación anual", "2025T1 - Variación en lo que va de año", "2024T4 - Variación en lo que va de año", "2024T3 - Variación en lo que va de año", "2024T2 - Variación en lo que va de año", "2024T1 - Variación en lo que va de año", "2023T4 - Variación en lo que va de año", "2023T3 - Variación en lo que va de año", "2023T2 - Variación en lo que va de año", "2023T1 - Variación en lo que va de año", "2022T4 - Variación en lo que va de año", "2022T3 - Variación en lo que va de año", "2022T2 - Variación en lo que va de año", "2022T1 - Variación en lo que va de año", "2021T4 - Variación en lo que va de año", "2021T3 - Variación en lo que va de año", "2021T2 - Variación en lo que va de año", "2021T1 - Variación en lo que va de año", "2020T4 - Variación en lo que va de año", "2020T3 - Variación en lo que va de año", "2020T2 - Variación en lo que va de año", "2020T1 - Variación en lo que va de año", "2019T4 - Variación en lo que va de año", "2019T3 - Variación en lo que va de año", "2019T2 - Variación en lo que va de año", "2019T1 - Variación en lo que va de año", "2018T4 - Variación en lo que va de año", "2018T3 - Variación en lo que va de año", "2018T2 - Variación en lo que va de año", "2018T1 - Variación en lo que va de año", "2017T4 - Variación en lo que va de año", "2017T3 - Variación en lo que va de año", "2017T2 - Variación en lo que va de año", "2017T1 - Variación en lo que va de año", "2016T4 - Variación en lo que va de año", "2016T3 - Variación en lo que va de año"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas reordenadas2",{{"CCAA1", "CCAA"}}),
				    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Columnas con nombre cambiado1", {"CCAA", "TipoVivienda"}, "Periodo-", "Valor"),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Otras columnas con anulación de dinamización", "Periodo-", Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv), {"Periodo", "Indicador"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Dividir columna por delimitador", "Fecha", each Date.FromText(Text.Combine({Text.Start([Periodo], 4), "-", Text.From(Number.From(Text.End([Periodo], 1))*3-2), "-01"}))),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Personalizada agregada1",{"Periodo"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas2",{{"CCAA", type text}, {"TipoVivienda", type text}, {"Indicador", type text}, {"Valor", type number}, {"Fecha", type date}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

